name: better_player
description: Advanced video player based on video_player and Chewie. It's solves many typical use cases and it's easy to run.
version: 0.0.5
authors:
  - Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/betterplayer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  open_iconic_flutter: ">=0.3.0 <0.4.0"
  video_player:
    git:
      url: https://github.com/jhomlala/plugins
      path: packages/video_player/video_player
      ref: reusable_video_controller

  wakelock: ">=0.1.2 <0.2.0"
  flutter_widgets: ^0.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: